#!/usr/bin/env bash

source /tmp/target/params
mkdir /tmp/{sync,private}

# Make an SSH key
rm /root/.ssh/id_ed25519
ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -C $target_hostname -N ""

# Make an age key for sops
nix run nixpkgs#ssh-to-age --extra-experimental-features 'flakes nix-command' \
  -- -private-key -i /root/.ssh/id_ed25519 > /tmp/sync/keys.txt
nix shell nixpkgs#age --extra-experimental-features 'flakes nix-command' \
  -c age-keygen -y /tmp/sync/keys.txt > /tmp/sync/age.pub

# Put files we want to keep in sync in the sync dir
cp /root/.ssh/id_ed25519.pub /tmp/sync/.

