#!/usr/bin/env bash

source /tmp/target/params

mkdir /tmp/{sync,private}
mv /root/.ssh/id_ed25519 /root/.ssh/id_ed25519-$(date +%s).bak
ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -C $target_hostname -N ""
cp /root/.ssh/id_ed25519.pub /tmp/sync/.

