#!/usr/bin/env bash
set -x

source /tmp/target/params

# Format the disks with disko
sudo nix --experimental-features 'nix-command flakes' \
  run github:nix-community/disko -- --mode disko /tmp/target/disko.nix

# 
# Find good github fingerprints with https
good_github_fingerprint=$(curl -s https://api.github.com/meta | \
  jq ."ssh_key_fingerprints" | awk -F\" '/ED25519/{print $4}')
echo $good_github_fingerprint > /tmp/good-fingerprint

# Find what fingerprints git cloning would find for us
ssh-keyscan github.com > /tmp/githubKey
real_github_fingerprint=$(ssh-keygen -lf /tmp/githubKey | \
  awk '/ED25519/{print $2}')

# If they match, then we can use it as a known host
if [[ "$real_github_fingerprint" == "SHA256:$good_github_fingerprint" ]]; then
  cat /tmp/githubKey | tee -a ~/.ssh/known_hosts
fi

# Get the repo
mkdir /mnt/etc/nixos
GIT_SSH_COMMAND="ssh -i /tmp/private/id_ed25519 -o IdentitiesOnly=yes" git clone $nix_config_repo /mnt/etc/nixos/

# Install
nixos-install --root /mnt --no-root-password \
  --flake /mnt/etc/nixos/#$target_hostname
